test_task:
  container:
    image: golang:latest
  modules_cache:
    fingerprint_script: cat go.sum
    folder: $GOPATH/pkg/mod
  get_script: go get -t -v ./...
  vet_script: go vet -v ./...
  test_script: go test -v ./...
